import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { API, useAuth } from '../auth/AuthContext'

type EventRow={id:number;event_code:string;name:string;category:string;organizing_department:string;event_date:string;venue:string;status:string;payment_type:string;fee:number;approval_comment?:string|null}
export default function ManagedEventsPage(){
  const {token,user}=useAuth(); const [rows,setRows]=useState<EventRow[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  async function load(){setLoading(true);try{const r=await fetch(`${API}/api/events/manage`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.rows||[])}catch(e){setError(e instanceof Error?e.message:'Could not load events.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[token])
  async function action(id:number,type:'submit'|'publish'){setError('');try{const r=await fetch(`${API}/api/events/${id}/${type}`,{method:'POST',headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:'Action failed.')}}
  return <section className="portal-content"><div className="page-toolbar"><div><span className="eyebrow">Event management</span><h2>My Events</h2><p>Drafts, approvals and published events in one place.</p></div><Link className="button button-primary" to="/coordinator/events/create">＋ Create Event</Link></div>{error&&<div className="form-alert error">{error}</div>}
  <div className="event-list-card">{loading?<div className="empty-state"><div className="spinner"/><p>Loading events…</p></div>:rows.length===0?<div className="empty-state"><div className="empty-icon">＋</div><h3>No events yet</h3><p>Create your first event and send it through approval.</p><Link className="button button-primary" to="/coordinator/events/create">Create Event</Link></div>:<div className="event-manage-list">{rows.map(e=><article key={e.id}><div className="event-date-tile"><b>{new Date(`${e.event_date}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit'})}</b><span>{new Date(`${e.event_date}T00:00:00`).toLocaleDateString('en-IN',{month:'short'})}</span></div><div className="event-manage-main"><div className="event-manage-top"><span className={`event-status status-${e.status.toLowerCase().split(' ').join('-')}`}>{e.status}</span><small>{e.event_code}</small></div><h3>{e.name}</h3><p>{e.category} • {e.organizing_department} • {e.venue}</p>{e.approval_comment&&<div className="approval-note">HOD note: {e.approval_comment}</div>}</div><div className="event-row-actions"><Link className="button button-ghost button-small" to={`/coordinator/events/${e.id}`}>Control Center</Link>{(user?.role==='Main Coordinator'||['Draft','Changes Requested'].includes(e.status))&&<Link className="button button-ghost button-small" to={`/coordinator/events/create?edit=${e.id}`}>Edit</Link>}{['Department Coordinator','Librarian'].includes(user?.role || '')&&['Draft','Changes Requested'].includes(e.status)&&<button className="button button-primary button-small" onClick={()=>action(e.id,'submit')}>Submit to HOD</button>}{e.status==='Approved'&&['Main Coordinator','Librarian'].includes(user?.role || '')&&<button className="button button-primary button-small" onClick={()=>action(e.id,'publish')}>Publish</button>}<span className="payment-mini">{e.payment_type==='Paid'?`₹${e.fee}`:'Free'}</span></div></article>)}</div>}</div></section>
}
