import { FormEvent, useEffect, useState } from 'react'
import { API, useAuth } from '../auth/AuthContext'

type Member={student_id:string;name:string;department:string;year:number;role:string;status:string}
type Team={participation_type:string;id:number;event_id:number;event_name:string;event_code:string;team_name:string;team_code:string;leader_student_id:string;leader_name:string;status:string;review_comment?:string|null;team_min:number;team_max:number;members:Member[]}
type EventOption={id:number;name:string;event_code:string;team_min:number;team_max:number;participation_type:string;allow_coordinator_teams:boolean}

export default function TeamManagementPage({ initialEventId = '' }: { initialEventId?: string } = {}){
  const {token}=useAuth();const [events,setEvents]=useState<EventOption[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [eventId,setEventId]=useState(initialEventId);const [status,setStatus]=useState('');const [q,setQ]=useState('');const [createEvent,setCreateEvent]=useState(initialEventId);const [teamName,setTeamName]=useState('');const [leaderId,setLeaderId]=useState('');const [members,setMembers]=useState('');const [memberInputs,setMemberInputs]=useState<Record<number,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('')
  async function load(){setError('');try{const er=await fetch(`${API}/api/team-events`,{headers:{Authorization:`Bearer ${token}`}});const ed=await er.json();if(!er.ok)throw new Error(ed.error);setEvents(ed.rows||[]);const params=new URLSearchParams();if(eventId)params.set('event_id',eventId);if(status)params.set('status',status);if(q)params.set('q',q);const tr=await fetch(`${API}/api/teams/manage?${params}`,{headers:{Authorization:`Bearer ${token}`}});const td=await tr.json();if(!tr.ok)throw new Error(td.error);setTeams(td.rows||[]);if(!createEvent&&ed.rows?.[0])setCreateEvent(String(ed.rows[0].id))}catch(e){setError(e instanceof Error?e.message:'Could not load teams.')}}
  useEffect(()=>{load()},[token,eventId,status])
  async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch(`${API}/api/teams`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({event_id:Number(createEvent),team_name:teamName,leader_student_id:leaderId,member_student_ids:members.split(',').map(x=>x.trim()).filter(Boolean)})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTeamName('');setLeaderId('');setMembers('');setMessage(`Team ${d.team.team_name} created. Review it when ready.`);await load()}catch(e){setError(e instanceof Error?e.message:'Could not create team.')}finally{setBusy(false)}}
  async function addMember(teamId:number){const sid=(memberInputs[teamId]||'').trim();if(!sid)return;setBusy(true);setError('');try{const r=await fetch(`${API}/api/teams/${teamId}/members`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({student_id:sid})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMemberInputs(p=>({...p,[teamId]:''}));await load()}catch(e){setError(e instanceof Error?e.message:'Could not add member.')}finally{setBusy(false)}}
  async function submit(teamId:number){setBusy(true);setError('');try{const r=await fetch(`${API}/api/teams/${teamId}/submit`,{method:'POST',headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:'Could not submit team.')}finally{setBusy(false)}}
  async function review(teamId:number,action:'approve'|'changes'|'reject'){let comment='';if(action!=='approve'){comment=window.prompt(action==='changes'?'What should the team correct?':'Reason for rejection?')?.trim()||'';if(!comment)return}setBusy(true);setError('');try{const r=await fetch(`${API}/api/teams/${teamId}/review`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action,comment})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(action==='approve'?'Team approved.':action==='changes'?'Changes requested from team.':'Team rejected.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not review team.')}finally{setBusy(false)}}
  async function changeLeader(team:Team,sid:string){if(sid===team.leader_student_id)return;setBusy(true);setError('');try{const r=await fetch(`${API}/api/teams/${team.id}/leader`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({student_id:sid})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:'Could not change leader.')}finally{setBusy(false)}}
  async function registerTeam(team:Team){if(busy)return;setBusy(true);setError('');setMessage('');try{const response=await fetch(`${API}/api/registrations`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({event_id:team.event_id,registration_type:'Team',team_id:team.id})});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage(`Team registered: ${data.registration.status}.`)}catch(error){setError(error instanceof Error?error.message:'Could not register team.')}finally{setBusy(false)}}
  return <section className="portal-content team-page"><div className="page-toolbar"><div><span className="eyebrow">Event Control Center</span><h2>Teams</h2><p>Create official teams, assign leaders, validate members and approve participation.</p></div></div>{error&&<div className="form-alert error">{error}</div>}{message&&<div className="form-alert success">{message}</div>}
    <div className="team-admin-grid"><form className="team-create-card" onSubmit={create}><span className="eyebrow">Coordinator assistance</span><h3>Create Team for Students</h3><p>For team-only events, select eligible students directly. For mixed events, students must register individually before joining a team.</p><label>Competition<select value={createEvent} onChange={e=>setCreateEvent(e.target.value)} required><option value="">Select event</option>{events.filter(e=>e.allow_coordinator_teams).map(e=><option value={e.id} key={e.id}>{e.name} • {e.event_code}</option>)}</select></label><label>Team Name<input value={teamName} onChange={e=>setTeamName(e.target.value)} required placeholder="Team name"/></label><label>Leader Student ID<input value={leaderId} onChange={e=>setLeaderId(e.target.value)} required placeholder="Registered Student ID"/></label><label>Other Member IDs<input value={members} onChange={e=>setMembers(e.target.value)} placeholder="Registered IDs: ID001, ID002, ID003"/></label><button className="button button-primary button-full" disabled={busy}>Create Team</button></form>
      <div className="team-section"><div className="team-filter-bar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search team, code, leader…" onKeyDown={e=>{if(e.key==='Enter')load()}}/><select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">All team events</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Draft','Pending','Approved','Changes Requested','Rejected','Locked'].map(x=><option key={x}>{x}</option>)}</select><button className="button button-ghost button-small" onClick={load}>Search</button></div>
        <div className="section-mini-head"><div><span className="eyebrow">Competition teams</span><h3>Team Directory</h3></div><span className="count-badge">{teams.length}</span></div>{teams.length===0?<div className="empty-state compact"><div className="empty-icon">◇</div><h3>No teams match</h3><p>Create a team or change your filters.</p></div>:<div className="team-stack">{teams.map(team=><article className="team-detail-card" key={team.id}><div className="team-title-row"><div><span>{team.event_code} • {team.team_code}</span><h3>{team.team_name}</h3><p>{team.event_name}</p></div><span className={`event-status status-${team.status.toLowerCase().replaceAll(' ','-')}`}>{team.status}</span></div><div className="team-summary-row"><div><small>Leader</small><b>{team.leader_name}</b></div><div><small>Team size</small><b>{team.members.filter(m=>m.status!=='Declined').length} / {team.team_max}</b></div><div><small>Required</small><b>{team.team_min}–{team.team_max}</b></div></div>{team.review_comment&&<div className="approval-note">Review note: {team.review_comment}</div>}<div className="member-list">{team.members.map(m=><div key={m.student_id}><span className="member-avatar">{m.name.slice(0,1)}</span><div><b>{m.name}</b><small>{m.student_id} • {m.department} • Year {m.year}</small></div><select className="member-role-select" value={m.role==='Leader'?m.student_id:''} onChange={()=>changeLeader(team,m.student_id)} title="Make team leader"><option value="">{m.status}</option>{m.role!=='Leader'&&<option value={m.student_id}>Make Leader</option>}{m.role==='Leader'&&<option value={m.student_id}>Leader</option>}</select></div>)}</div>{['Draft','Changes Requested'].includes(team.status)&&<div className="team-manage-row"><input value={memberInputs[team.id]||''} onChange={e=>setMemberInputs(p=>({...p,[team.id]:e.target.value}))} placeholder="Add member by Student ID"/><button className="button button-ghost button-small" onClick={()=>addMember(team.id)}>Add</button><button className="button button-primary button-small" onClick={()=>submit(team.id)}>Send for Review</button></div>}{team.status==='Approved'&&team.participation_type==='Team'&&<button className="button button-primary" disabled={busy} onClick={()=>registerTeam(team)}>Register approved team</button>}{['Pending','Changes Requested'].includes(team.status)&&<div className="review-action-row"><button className="button success-button button-small" disabled={busy} onClick={()=>review(team.id,'approve')}>Approve Team</button><button className="button warning-button button-small" disabled={busy} onClick={()=>review(team.id,'changes')}>Request Changes</button><button className="button danger-button button-small" disabled={busy} onClick={()=>review(team.id,'reject')}>Reject</button></div>}</article>)}</div>}</div></div>
  </section>
}
