import { Link, useLocation } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'

type Card={title:string;description:string;href?:string;tag?:string}
const sets:Record<string,{title:string;subtitle:string;cards:Card[]}>= {
  '/admin/departments':{title:'Department Management',subtitle:'Manage college departments and departmental event visibility.',cards:[
    {title:'CSE',description:'Computer Science & Engineering'},{title:'Civil',description:'Civil Engineering'},{title:'Mechanical',description:'Mechanical Engineering'},{title:'Electrical',description:'Electrical Engineering'},{title:'EEE',description:'Electrical & Electronics Engineering'}]},
  '/admin/library':{title:'Library Management',subtitle:'Dedicated workspace for library competitions and activities.',cards:[
    {title:'Reading Competition',description:'Create and manage reading competitions.'},{title:'Quiz Competition',description:'Library quiz events and results.'},{title:'Orientation Program',description:'Student orientation activities.'},{title:'Library Activities',description:'All other library-led activities.'}]},
  '/admin/venues':{title:'Venue Management',subtitle:'Maintain venues and prepare for clash detection.',cards:[
    {title:'Auditorium',description:'Large college events'},{title:'Seminar Hall',description:'Talks, seminars and workshops'},{title:'Classrooms',description:'Department-level sessions'},{title:'Computer Labs',description:'Technical competitions'},{title:'Library Hall',description:'Library events'},{title:'Sports Ground',description:'Sports and outdoor activities'}]},
  '/admin/calendar':{title:'Schedule & Calendar',subtitle:'One college calendar for events, venues and time slots.',cards:[
    {title:'Event Calendar',description:'Upcoming and completed college events.'},{title:'Time Slots',description:'Reusable event time slots.'},{title:'Event Timeline',description:'Track each event from draft to archive.'},{title:'Clash Detection',description:'Detect venue/date/time conflicts before publishing.'}]},
  '/admin/reports':{title:'Reports & Analytics',subtitle:'Exportable reports based only on real EventHub records.',cards:[
    {title:'Event Reports',description:'Registrations, attendance, results and remarks.'},{title:'Department Reports',description:'Participation across departments.'},{title:'Payment Reports',description:'Online/offline collection and pending payments.'},{title:'Attendance Reports',description:'Event and student attendance.'},{title:'Achievement Reports',description:'Verified wins, points and badges.'},{title:'Export Center',description:'CSV/Excel/PDF exports respecting filters.'}]},
  '/admin/rankings':{title:'Achievement & Ranking Settings',subtitle:'Configure transparent, editable achievement rules.',cards:[
    {title:'Point Rules',description:'Edit points for 1st, 2nd, 3rd, finalist, participation, volunteering and workshops.'},{title:'Badges',description:'Manage achievement badge rules.'},{title:'Leaderboards',description:'Overall, category, department, year and team rankings.'},{title:'Department Cup',description:'Weighted department performance leaderboard.'}]},
  '/admin/notifications':{title:'Notification Center',subtitle:'In-app first, with email and WhatsApp adapters configured when credentials are available.',cards:[
    {title:'In-App',description:'Announcements and account notifications.'},{title:'Email',description:'Gmail/Google Workspace SMTP configuration.'},{title:'WhatsApp',description:'Meta WhatsApp Business Platform templates.'},{title:'Audience Builder',description:'Registered, pending, attendees, winners and other event groups.'}]},
  '/admin/audit':{title:'Audit & Security',subtitle:'Important changes remain attributable and reviewable.',cards:[
    {title:'Admin Actions',description:'User, event and system changes.'},{title:'Payment Audit',description:'Payment corrections and void history.'},{title:'Attendance Changes',description:'Authorized attendance corrections.'},{title:'Result Changes',description:'Result revisions before and after publish.'},{title:'Login History',description:'Authentication activity foundation.'}]},
  '/admin/settings':{title:'Settings',subtitle:'College-wide configurable settings.',cards:[
    {title:'College Information',description:'GEMS Polytechnic College branding and details.'},{title:'Event Categories',description:'College, Department, Library, Sports, Cultural, Technical and more.'},{title:'Roles & Permissions',description:'Server-side role and department restrictions.'},{title:'Academic Years',description:'Academic year, semester and promotion settings.'},{title:'Payment Settings',description:'Razorpay and offline Cash/UPI collection.'},{title:'Certificate Settings',description:'Common and event-specific templates/signatories.'},{title:'Branding & Theme',description:'GEMS blue/cyan, navy, gold; light and dark mode.'},{title:'Backup & Restore',description:'Local backup foundation and production backup policy.'}]},
  '/coordinator/students':{title:'Student Search',subtitle:'Find eligible students and assist registrations without requiring a smartphone.',cards:[{title:'Search Directory',description:'Search by Student ID, name, roll number or barcode.',href:'/coordinator/students/search'},{title:'Assist Registration',description:'Register a student for an assigned event.',href:'/coordinator/students/registration'},{title:'Offline Payment',description:'Record authorized Cash or coordinator UPI collections.',href:'/coordinator/students/payment'},{title:'Identity Fallback',description:'If ID is unavailable, coordinator can manually compare the stored student photo and approve with an audit reason.',href:'/coordinator/students/identity'}]},
  '/coordinator/notifications':{title:'Event Communication',subtitle:'Send targeted event communication to participants.',cards:[{title:'Registered Students',description:'Notify all registered participants.',href:'/coordinator/notifications/registered'},{title:'Payment Pending',description:'Target unpaid/pending registrations.',href:'/coordinator/notifications/payment-pending'},{title:'Team Leaders',description:'Send team-level instructions.',href:'/coordinator/notifications/team-leaders'},{title:'Attendees & Winners',description:'Post-event updates and certificates.',href:'/coordinator/notifications/attendees-winners'}]},
  '/coordinator/reports':{title:'Coordinator Reports',subtitle:'Reports limited to assigned events and permitted departments.',cards:[{title:'Registration Report',description:'Confirmed, pending and waiting list.',href:'/coordinator/reports/registrations'},{title:'Payment Reconciliation',description:'Online/offline totals by department coordinator.',href:'/coordinator/reports/payments'},{title:'Attendance',description:'Check-in report and corrections.',href:'/coordinator/reports/attendance'},{title:'Final Event Report',description:'One complete event record for the college archive.',href:'/coordinator/reports/final'}]},
  '/hod/calendar':{title:'Department Calendar',subtitle:'View approved and pending department activities.',cards:[{title:'Upcoming',description:'Upcoming department events.'},{title:'Pending Approval',description:'Events waiting for review.'},{title:'Completed',description:'Completed department record.'}]},
  '/hod/reports':{title:'Department Reports',subtitle:'Read-only department-level event reporting.',cards:[{title:'Participation',description:'Student registration records.',href:'/hod/reports/registrations'},{title:'Payments',description:'Department payment records.',href:'/hod/reports/payments'},{title:'Attendance',description:'Event attendance summaries.',href:'/hod/reports/attendance'}]},
}
export default function WorkspacePage(){
 const {pathname}=useLocation(); const {user}=useAuth(); const data=sets[pathname]||{title:'Workspace',subtitle:'This module is ready for the next operational workflow.',cards:[]}
 return <div className="page-stack"><section className="page-hero compact"><div><span className="eyebrow">{user?.role} workspace</span><h2>{data.title}</h2><p>{data.subtitle}</p></div></section><section className="feature-grid">{data.cards.map(c=><article className="feature-card" key={c.title}><div className="feature-icon" aria-hidden="true">&#9670;</div><h3>{c.title}</h3><p>{c.description}</p>{c.href&&<Link className="text-link" to={c.href}>Open <span aria-hidden="true">&rarr;</span></Link>}</article>)}</section></div>
}





