import { lazy, Suspense } from 'react'
const DepartmentCalendarPage = lazy(() => import('./pages/DepartmentCalendarPage'))
import {Navigate,Route,Routes} from 'react-router-dom'
const CoordinatorAttendanceReportPage = lazy(() => import('./pages/CoordinatorAttendanceReportPage'))
const AdminOperationsPage = lazy(() => import('./pages/AdminOperationsPage'))
const AdminSheetsPage = lazy(() => import('./pages/AdminSheetsPage'))
import PublicLayout from './layouts/PublicLayout';import PortalLayout from './layouts/PortalLayout';import RequireAuth from './auth/RequireAuth'
const CoordinatorStudentsPage = lazy(() => import('./pages/CoordinatorStudentsPage'));
const CoordinatorAssistRegistrationPage = lazy(() => import('./pages/CoordinatorAssistRegistrationPage'));
const CoordinatorOfflinePaymentPage = lazy(() => import('./pages/CoordinatorOfflinePaymentPage'));
const CoordinatorIdentityFallbackPage = lazy(() => import('./pages/CoordinatorIdentityFallbackPage'));
const AdminRegistrationsPage = lazy(() => import('./pages/AdminRegistrationsPage'));const HomePage = lazy(() => import('./pages/HomePage'));const EventsPage = lazy(() => import('./pages/EventsPage'));const StudentExplorePage = lazy(() => import('./pages/StudentExplorePage'));const StudentPaymentsPage = lazy(() => import('./pages/StudentPaymentsPage'));const StudentResultsPage = lazy(() => import('./pages/StudentResultsPage'));const StudentCertificatesPage = lazy(() => import('./pages/StudentCertificatesPage'));const StudentProfilePage = lazy(() => import('./pages/StudentProfilePage'));const LoginPage = lazy(() => import('./pages/LoginPage'));const SetupPage = lazy(() => import('./pages/SetupPage'));const StudentDashboard = lazy(() => import('./pages/StudentDashboard'));const CoordinatorDashboard = lazy(() => import('./pages/CoordinatorDashboard'));const ScannerPage = lazy(() => import('./pages/ScannerPage'));const AdminDashboard = lazy(() => import('./pages/AdminDashboard'));const StudentsPage = lazy(() => import('./pages/StudentsPage'));const UsersPage = lazy(() => import('./pages/UsersPage'));const HodDashboard = lazy(() => import('./pages/HodDashboard'));const ForbiddenPage = lazy(() => import('./pages/ForbiddenPage'));const NotFoundPage = lazy(() => import('./pages/NotFoundPage'));const CreateEventPage = lazy(() => import('./pages/CreateEventPage'));const ManagedEventsPage = lazy(() => import('./pages/ManagedEventsPage'));const HodApprovalsPage = lazy(() => import('./pages/HodApprovalsPage'));const AdminEventsPage = lazy(() => import('./pages/AdminEventsPage'));const MyTeamsPage = lazy(() => import('./pages/MyTeamsPage'));const TeamManagementPage = lazy(() => import('./pages/TeamManagementPage'));const EventControlCenterPage = lazy(() => import('./pages/EventControlCenterPage'));const StudentRegistrationsPage = lazy(() => import('./pages/StudentRegistrationsPage'));const WorkspacePage = lazy(() => import('./pages/WorkspacePage'))
const CoordinatorRegisteredStudentsNotificationPage = lazy(() => import('./pages/CoordinatorRegisteredStudentsNotificationPage'));const CoordinatorPaymentPendingNotificationPage = lazy(() => import('./pages/CoordinatorPaymentPendingNotificationPage'));const CoordinatorTeamLeadersNotificationPage = lazy(() => import('./pages/CoordinatorTeamLeadersNotificationPage'));const CoordinatorAttendeesWinnersNotificationPage = lazy(() => import('./pages/CoordinatorAttendeesWinnersNotificationPage'));const CoordinatorRegistrationReportPage = lazy(() => import('./pages/CoordinatorRegistrationReportPage'));const CoordinatorPaymentReconciliationPage = lazy(() => import('./pages/CoordinatorPaymentReconciliationPage'));const CoordinatorFinalEventReportPage = lazy(() => import('./pages/CoordinatorFinalEventReportPage'));const RankingsPage = lazy(() => import('./pages/RankingsPage'));const StudentActivityPage = lazy(() => import('./pages/StudentActivityPage'));const NotificationsPage = lazy(() => import('./pages/NotificationsPage'));const PublicResultsPage = lazy(() => import('./pages/PublicResultsPage'));const PublicGalleryPage = lazy(() => import('./pages/PublicGalleryPage'));const CertificateVerifyPage = lazy(() => import('./pages/CertificateVerifyPage'));const ContactPage = lazy(() => import('./pages/ContactPage'));const AdminGalleryPage = lazy(() => import('./pages/AdminGalleryPage'))
export default function App(){return <Suspense fallback={<div className="empty-state" role="status">Loading page…</div>}><Routes><Route element={<PublicLayout/>}><Route path="/" element={<HomePage/>}/><Route path="/events" element={<EventsPage/>}/><Route path="/results" element={<PublicResultsPage/>}/><Route path="/gallery" element={<PublicGalleryPage/>}/><Route path="/verify" element={<CertificateVerifyPage/>}/><Route path="/contact" element={<ContactPage/>}/><Route path="/login" element={<LoginPage/>}/></Route><Route path="/setup" element={<SetupPage/>}/><Route path="/forbidden" element={<ForbiddenPage/>}/>
<Route element={<RequireAuth roles={['Student']}/>}> <Route path="/student" element={<PortalLayout/>}><Route index element={<StudentDashboard/>}/><Route path="explore" element={<StudentExplorePage/>}/><Route path="registrations" element={<StudentRegistrationsPage/>}/><Route path="payments" element={<StudentPaymentsPage/>}/><Route path="teams" element={<MyTeamsPage/>}/><Route path="rankings" element={<RankingsPage/>}/><Route path="activity" element={<StudentActivityPage/>}/><Route path="results" element={<StudentResultsPage/>}/><Route path="certificates" element={<StudentCertificatesPage/>}/><Route path="notifications" element={<NotificationsPage/>}/><Route path="profile" element={<StudentProfilePage/>}/></Route></Route>
<Route element={<RequireAuth roles={['Main Coordinator','Department Coordinator','Librarian']}/>}> <Route path="/coordinator" element={<PortalLayout/>}><Route index element={<CoordinatorDashboard/>}/><Route path="events" element={<ManagedEventsPage/>}/><Route path="events/create" element={<CreateEventPage/>}/><Route path="events/:eventId" element={<EventControlCenterPage/>}/><Route path="teams" element={<TeamManagementPage/>}/><Route path="scanner" element={<ScannerPage/>}/><Route path="students" element={<WorkspacePage/>}/><Route path="students/search" element={<CoordinatorStudentsPage/>}/><Route path="students/registration" element={<CoordinatorAssistRegistrationPage/>}/><Route path="students/payment" element={<CoordinatorOfflinePaymentPage/>}/><Route path="students/identity" element={<CoordinatorIdentityFallbackPage/>}/><Route path="inbox" element={<NotificationsPage/>}/><Route path="notifications" element={<WorkspacePage/>}/>
          <Route path="notifications/registered" element={<CoordinatorRegisteredStudentsNotificationPage/>}/><Route path="notifications/payment-pending" element={<CoordinatorPaymentPendingNotificationPage/>}/><Route path="notifications/team-leaders" element={<CoordinatorTeamLeadersNotificationPage/>}/><Route path="notifications/attendees-winners" element={<CoordinatorAttendeesWinnersNotificationPage/>}/><Route path="reports" element={<WorkspacePage/>}/><Route path="reports/registrations" element={<CoordinatorRegistrationReportPage/>}/><Route path="reports/payments" element={<CoordinatorPaymentReconciliationPage/>}/><Route path="reports/attendance" element={<CoordinatorAttendanceReportPage/>}/><Route path="reports/final" element={<CoordinatorFinalEventReportPage/>}/></Route></Route>
<Route element={<RequireAuth roles={['HOD']}/>}> <Route path="/hod" element={<PortalLayout/>}><Route index element={<HodDashboard/>}/><Route path="approvals" element={<HodApprovalsPage/>}/><Route path="calendar" element={<DepartmentCalendarPage/>}/><Route path="notifications" element={<NotificationsPage/>}/><Route path="reports" element={<WorkspacePage/>}/><Route path="reports/registrations" element={<CoordinatorRegistrationReportPage/>}/><Route path="reports/payments" element={<CoordinatorPaymentReconciliationPage/>}/><Route path="reports/attendance" element={<CoordinatorAttendanceReportPage/>}/></Route></Route>
<Route element={<RequireAuth roles={['Super Admin']}/>}> <Route path="/admin" element={<PortalLayout/>}><Route index element={<AdminDashboard/>}/><Route path="events" element={<AdminEventsPage/>}/><Route path="events/:eventId" element={<EventControlCenterPage/>}/><Route path="events/create" element={<CreateEventPage/>}/><Route path="students" element={<StudentsPage/>}/><Route path="registrations" element={<AdminRegistrationsPage/>}/><Route path="users" element={<UsersPage/>}/><Route path="gallery" element={<AdminGalleryPage/>}/><Route path="sheets" element={<AdminSheetsPage/>}/>{['departments','library','venues','calendar','reports','rankings','audit','notifications','settings'].map(p=><Route key={p} path={p} element={<AdminOperationsPage/>}/>)}</Route></Route><Route path="/home" element={<Navigate to="/" replace/>}/><Route path="*" element={<NotFoundPage/>}/></Routes></Suspense>}



